server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.php index.html;
    client_max_body_size 100M;
    include /etc/nginx/install-block.conf;
    resolver 127.0.0.11 valid=10s;
    location / {
        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php?s=$1 last;
        }
    }
    location ~ /\. { deny all; }
    location ~* ^/uploads/.*\.(php|phtml|phar)(/|$) { deny all; }
    location /notice {
        set $backend workerman:40001;
        rewrite ^/notice/?(.*)$ /$1 break;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
    }
    location /msg {
        set $backend workerman:40002;
        rewrite ^/msg/?(.*)$ /$1 break;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
    }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}
