-- +----------------------------------------------------------------------
-- | CRMEB 多言語パッチ: 中国語 / English / 日本語 の3言語対応
-- +----------------------------------------------------------------------
-- | 適用: mysql -u<user> -p <database> < lang_zh_en_ja.sql
-- | 適用後、管理画面のキャッシュクリア（またはキャッシュ削除）を実行してください。
-- | テーブル接頭辞が eb_ 以外の場合は一括置換してください。
-- +----------------------------------------------------------------------

SET NAMES utf8mb4;

-- ============================================================
-- 1. 言語タイプ: 中国語(1) / English(2) / 日本語(6) のみ有効化
--    ※ 他言語は status=0 にするだけでデータは残すため、いつでも再有効化できます。
-- ============================================================
UPDATE `eb_lang_type` SET `status` = 1 WHERE `id` IN (1, 2, 6);
UPDATE `eb_lang_type` SET `status` = 0 WHERE `id` NOT IN (1, 2, 6);

-- ============================================================
-- 2. ブラウザ言語コード → 言語タイプ の対応を補完
--    既存は 'zh-CN' / 'en-US' / 'ja-JP' のみ対応しており、
--    navigator.language が 'ja' や 'en-GB' を返す環境で中国語に
--    フォールバックしてしまうため、変種コードも割り当てます。
-- ============================================================
UPDATE `eb_lang_country` SET `type_id` = 6 WHERE `code` IN ('ja', 'ja-JP');
UPDATE `eb_lang_country` SET `type_id` = 2 WHERE `code` = 'en' OR `code` LIKE 'en-%';
UPDATE `eb_lang_country` SET `type_id` = 1 WHERE `code` IN ('zh', 'zh-CN', 'zh-Hans', 'zh-SG');

-- 'zh-Hans' は初期データに存在しないため、無ければ追加
INSERT INTO `eb_lang_country` (`type_id`, `code`, `name`)
SELECT 1, 'zh-Hans', '中文(简体)' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `eb_lang_country` WHERE `code` = 'zh-Hans');

-- ============================================================
-- 3. 言語パックに欠落しているコードを追加
-- ============================================================
-- ============================================================
-- 4. 日本語訳の補正（未翻訳の穴埋め + 機械翻訳の誤訳修正）
--    crmeb/app/lang/ja_jp.php と同じ訳語になるよう揃えています。
-- ============================================================
UPDATE `eb_lang_code` SET `lang_explain` = '保存しました' WHERE `type_id` = 6 AND `code` = '100000';
UPDATE `eb_lang_code` SET `lang_explain` = '変更しました' WHERE `type_id` = 6 AND `code` = '100001';
UPDATE `eb_lang_code` SET `lang_explain` = '削除しました' WHERE `type_id` = 6 AND `code` = '100002';
UPDATE `eb_lang_code` SET `lang_explain` = '表示しました' WHERE `type_id` = 6 AND `code` = '100003';
UPDATE `eb_lang_code` SET `lang_explain` = '非表示にしました' WHERE `type_id` = 6 AND `code` = '100004';
UPDATE `eb_lang_code` SET `lang_explain` = '画像をアップロードしました' WHERE `type_id` = 6 AND `code` = '100009';
UPDATE `eb_lang_code` SET `lang_explain` = '操作が完了しました' WHERE `type_id` = 6 AND `code` = '100010';
UPDATE `eb_lang_code` SET `lang_explain` = '更新しました' WHERE `type_id` = 6 AND `code` = '100012';
UPDATE `eb_lang_code` SET `lang_explain` = '設定しました' WHERE `type_id` = 6 AND `code` = '100014';
UPDATE `eb_lang_code` SET `lang_explain` = '送信しました' WHERE `type_id` = 6 AND `code` = '100017';
UPDATE `eb_lang_code` SET `lang_explain` = 'キャンセルしました' WHERE `type_id` = 6 AND `code` = '100019';
UPDATE `eb_lang_code` SET `lang_explain` = '追加しました' WHERE `type_id` = 6 AND `code` = '100021';
UPDATE `eb_lang_code` SET `lang_explain` = '備考を保存しました' WHERE `type_id` = 6 AND `code` = '100024';
UPDATE `eb_lang_code` SET `lang_explain` = '申請しました' WHERE `type_id` = 6 AND `code` = '100027';
UPDATE `eb_lang_code` SET `lang_explain` = '送信しました' WHERE `type_id` = 6 AND `code` = '100030';
UPDATE `eb_lang_code` SET `lang_explain` = 'アップロードしました' WHERE `type_id` = 6 AND `code` = '100032';
UPDATE `eb_lang_code` SET `lang_explain` = '返金しました' WHERE `type_id` = 6 AND `code` = '100036';
UPDATE `eb_lang_code` SET `lang_explain` = '復元しました' WHERE `type_id` = 6 AND `code` = '100040';
UPDATE `eb_lang_code` SET `lang_explain` = '開通しました' WHERE `type_id` = 6 AND `code` = '100044';
UPDATE `eb_lang_code` SET `lang_explain` = 'データを消去しました' WHERE `type_id` = 6 AND `code` = '100046';
UPDATE `eb_lang_code` SET `lang_explain` = '最適化しました' WHERE `type_id` = 6 AND `code` = '100047';
UPDATE `eb_lang_code` SET `lang_explain` = '修復しました' WHERE `type_id` = 6 AND `code` = '100049';
UPDATE `eb_lang_code` SET `lang_explain` = 'バックアップしました' WHERE `type_id` = 6 AND `code` = '100051';
UPDATE `eb_lang_code` SET `lang_explain` = 'パラメータエラー' WHERE `type_id` = 6 AND `code` = '100100';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインステータスが正しくありません。もう一度ログインしてください' WHERE `type_id` = 6 AND `code` = '110004';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインステータスが正しくありません。もう一度ログインしてください' WHERE `type_id` = 6 AND `code` = '110007';
UPDATE `eb_lang_code` SET `lang_explain` = 'サービススコアを選択してください' WHERE `type_id` = 6 AND `code` = '400004';
UPDATE `eb_lang_code` SET `lang_explain` = '商品スコアは1～5の整数でなければなりません' WHERE `type_id` = 6 AND `code` = '400005';
UPDATE `eb_lang_code` SET `lang_explain` = 'サービススコアは1～5の整数でなければなりません' WHERE `type_id` = 6 AND `code` = '400006';
UPDATE `eb_lang_code` SET `lang_explain` = 'クラウドプリンターの番号を入力してください' WHERE `type_id` = 6 AND `code` = '400012';
UPDATE `eb_lang_code` SET `lang_explain` = 'タイプデータ形式エラー、1または2または3である必要があります' WHERE `type_id` = 6 AND `code` = '400029';
UPDATE `eb_lang_code` SET `lang_explain` = '任命データ形式が正しくありません。0または1である必要があります' WHERE `type_id` = 6 AND `code` = '400030';
UPDATE `eb_lang_code` SET `lang_explain` = 'no_delivery データ形式エラー、0または1でなければなりません' WHERE `type_id` = 6 AND `code` = '400031';
UPDATE `eb_lang_code` SET `lang_explain` = 'レベルデータ形式エラー、整数でなければなりません' WHERE `type_id` = 6 AND `code` = '400039';
UPDATE `eb_lang_code` SET `lang_explain` = '第1レベルのリベート率は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400042';
UPDATE `eb_lang_code` SET `lang_explain` = '第1レベルのリベート率は小数点以下2桁までです' WHERE `type_id` = 6 AND `code` = '400043';
UPDATE `eb_lang_code` SET `lang_explain` = '第1レベルのリベート率は0～100の範囲を満たします' WHERE `type_id` = 6 AND `code` = '400044';
UPDATE `eb_lang_code` SET `lang_explain` = '第2レベルのリベート率は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400045';
UPDATE `eb_lang_code` SET `lang_explain` = '第2レベルのリベート率は小数点以下2桁までです' WHERE `type_id` = 6 AND `code` = '400046';
UPDATE `eb_lang_code` SET `lang_explain` = '第2レベルのリベート率は0～100の範囲を満たします' WHERE `type_id` = 6 AND `code` = '400047';
UPDATE `eb_lang_code` SET `lang_explain` = '最低出金額は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400051';
UPDATE `eb_lang_code` SET `lang_explain` = 'コミッションの凍結時間の範囲は0～180です' WHERE `type_id` = 6 AND `code` = '400052';
UPDATE `eb_lang_code` SET `lang_explain` = '控除可能なポイントのパーセンテージは、小数点以下2桁までです' WHERE `type_id` = 6 AND `code` = '400055';
UPDATE `eb_lang_code` SET `lang_explain` = 'クレジットポイントのパーセンテージは0から1000の間でなければなりません' WHERE `type_id` = 6 AND `code` = '400056';
UPDATE `eb_lang_code` SET `lang_explain` = '減点の上限は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400058';
UPDATE `eb_lang_code` SET `lang_explain` = '注文ボーナスポイントは数字でなければなりません' WHERE `type_id` = 6 AND `code` = '400059';
UPDATE `eb_lang_code` SET `lang_explain` = 'オーダーボーナスポイントは0～1000の間でなければなりません' WHERE `type_id` = 6 AND `code` = '400060';
UPDATE `eb_lang_code` SET `lang_explain` = '整数倍は0より大きい必要があります' WHERE `type_id` = 6 AND `code` = '400067';
UPDATE `eb_lang_code` SET `lang_explain` = '割引の数は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400068';
UPDATE `eb_lang_code` SET `lang_explain` = '整数倍は0より大きい必要があります' WHERE `type_id` = 6 AND `code` = '400069';
UPDATE `eb_lang_code` SET `lang_explain` = '割引の数は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400070';
UPDATE `eb_lang_code` SET `lang_explain` = '注文ボーナスの経験率は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400072';
UPDATE `eb_lang_code` SET `lang_explain` = 'サインインエクスペリエンスは0より大きい必要があります' WHERE `type_id` = 6 AND `code` = '400074';
UPDATE `eb_lang_code` SET `lang_explain` = '新しいユーザーを経験値として招待するには、0より大きくする必要があります' WHERE `type_id` = 6 AND `code` = '400076';
UPDATE `eb_lang_code` SET `lang_explain` = '送信者名の長さは2～10桁です' WHERE `type_id` = 6 AND `code` = '400078';
UPDATE `eb_lang_code` SET `lang_explain` = '送信者のアドレスの長さは10～100桁です' WHERE `type_id` = 6 AND `code` = '400082';
UPDATE `eb_lang_code` SET `lang_explain` = '電子シングルプリンターのシリアル番号の長さは10～50桁です' WHERE `type_id` = 6 AND `code` = '400084';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスのフィードバックの長さは10～90桁です' WHERE `type_id` = 6 AND `code` = '400085';
UPDATE `eb_lang_code` SET `lang_explain` = '金額を0未満にすることはできません' WHERE `type_id` = 6 AND `code` = '400095';
UPDATE `eb_lang_code` SET `lang_explain` = 'お名前を入力してください' WHERE `type_id` = 6 AND `code` = '400107';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取りを完了しました' WHERE `type_id` = 6 AND `code` = '400117';
UPDATE `eb_lang_code` SET `lang_explain` = '印刷しました' WHERE `type_id` = 6 AND `code` = '400121';
UPDATE `eb_lang_code` SET `lang_explain` = '追加された検証担当者ユーザーは既に存在します' WHERE `type_id` = 6 AND `code` = '400126';
UPDATE `eb_lang_code` SET `lang_explain` = '検証担当者の名前を記入してください' WHERE `type_id` = 6 AND `code` = '400128';
UPDATE `eb_lang_code` SET `lang_explain` = '検証担当者を追加しました' WHERE `type_id` = 6 AND `code` = '400130';
UPDATE `eb_lang_code` SET `lang_explain` = '検証担当者の追加に失敗しました' WHERE `type_id` = 6 AND `code` = '400131';
UPDATE `eb_lang_code` SET `lang_explain` = '最長の SMS 署名は8桁です' WHERE `type_id` = 6 AND `code` = '400136';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインしました' WHERE `type_id` = 6 AND `code` = '400139';
UPDATE `eb_lang_code` SET `lang_explain` = 'アフターサービス注文のステータスではこの操作を実行できません' WHERE `type_id` = 6 AND `code` = '400144';
UPDATE `eb_lang_code` SET `lang_explain` = '返金ステータスを変更しました' WHERE `type_id` = 6 AND `code` = '400145';
UPDATE `eb_lang_code` SET `lang_explain` = '返金しました' WHERE `type_id` = 6 AND `code` = '400149';
UPDATE `eb_lang_code` SET `lang_explain` = '認証に成功しました' WHERE `type_id` = 6 AND `code` = '400151';
UPDATE `eb_lang_code` SET `lang_explain` = '検証しました' WHERE `type_id` = 6 AND `code` = '400152';
UPDATE `eb_lang_code` SET `lang_explain` = '検証注文が見つかりません' WHERE `type_id` = 6 AND `code` = '400153';
UPDATE `eb_lang_code` SET `lang_explain` = 'ポイントを返却しました' WHERE `type_id` = 6 AND `code` = '400164';
UPDATE `eb_lang_code` SET `lang_explain` = '返信しました' WHERE `type_id` = 6 AND `code` = '400169';
UPDATE `eb_lang_code` SET `lang_explain` = '登録しました' WHERE `type_id` = 6 AND `code` = '400170';
UPDATE `eb_lang_code` SET `lang_explain` = 'パッケージリストの取得に失敗しました' WHERE `type_id` = 6 AND `code` = '400173';
UPDATE `eb_lang_code` SET `lang_explain` = '最初に電子フェイスシングルプリントサービスを有効にしてください' WHERE `type_id` = 6 AND `code` = '400177';
UPDATE `eb_lang_code` SET `lang_explain` = 'SMS署名を変更しました' WHERE `type_id` = 6 AND `code` = '400180';
UPDATE `eb_lang_code` SET `lang_explain` = 'プロトコルタイプが存在しません' WHERE `type_id` = 6 AND `code` = '400184';
UPDATE `eb_lang_code` SET `lang_explain` = '消去しました' WHERE `type_id` = 6 AND `code` = '400185';
UPDATE `eb_lang_code` SET `lang_explain` = 'データを追加しました' WHERE `type_id` = 6 AND `code` = '400189';
UPDATE `eb_lang_code` SET `lang_explain` = '0-23時より前の整数を入力してください' WHERE `type_id` = 6 AND `code` = '400192';
UPDATE `eb_lang_code` SET `lang_explain` = '1時から24時までの整数を入力してください' WHERE `type_id` = 6 AND `code` = '400193';
UPDATE `eb_lang_code` SET `lang_explain` = '開始時間 + 継続時間は24時間を超えることはできません' WHERE `type_id` = 6 AND `code` = '400194';
UPDATE `eb_lang_code` SET `lang_explain` = '0以上の整数を入力してください' WHERE `type_id` = 6 AND `code` = '400197';
UPDATE `eb_lang_code` SET `lang_explain` = '第2レベルのリベートの比率は、第1レベルより大きくすることはできません' WHERE `type_id` = 6 AND `code` = '400203';
UPDATE `eb_lang_code` SET `lang_explain` = 'レベルを追加しました' WHERE `type_id` = 6 AND `code` = '400205';
UPDATE `eb_lang_code` SET `lang_explain` = 'タスクを追加しました' WHERE `type_id` = 6 AND `code` = '400210';
UPDATE `eb_lang_code` SET `lang_explain` = '贈呈しました' WHERE `type_id` = 6 AND `code` = '400218';
UPDATE `eb_lang_code` SET `lang_explain` = '少なくとも1つの権限を選択してください' WHERE `type_id` = 6 AND `code` = '400221';
UPDATE `eb_lang_code` SET `lang_explain` = '最初にスペースドメイン名を設定してください' WHERE `type_id` = 6 AND `code` = '400225';
UPDATE `eb_lang_code` SET `lang_explain` = 'クラウドストレージの切り替えに成功しました。ストレージスペースが有効になっているかどうかを確認してください' WHERE `type_id` = 6 AND `code` = '400228';
UPDATE `eb_lang_code` SET `lang_explain` = 'ローカルストレージの切り替えに成功しました' WHERE `type_id` = 6 AND `code` = '400229';
UPDATE `eb_lang_code` SET `lang_explain` = 'テンプレートメッセージを追加しました' WHERE `type_id` = 6 AND `code` = '400235';
UPDATE `eb_lang_code` SET `lang_explain` = '少なくとも1つのボタンを追加してください' WHERE `type_id` = 6 AND `code` = '400238';
UPDATE `eb_lang_code` SET `lang_explain` = '最初に WeChat パブリックアカウント appid、appSecret およびその他のパラメーターを構成してください' WHERE `type_id` = 6 AND `code` = '400248';
UPDATE `eb_lang_code` SET `lang_explain` = 'テンプレートメッセージのワンクリック設定が成功しました' WHERE `type_id` = 6 AND `code` = '400249';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスは既に存在します' WHERE `type_id` = 6 AND `code` = '400253';
UPDATE `eb_lang_code` SET `lang_explain` = '口座番号は4～30桁または文字の組み合わせである必要があります' WHERE `type_id` = 6 AND `code` = '400255';
UPDATE `eb_lang_code` SET `lang_explain` = 'パスワードは6～20桁の数字または文字の組み合わせである必要があります' WHERE `type_id` = 6 AND `code` = '400257';
UPDATE `eb_lang_code` SET `lang_explain` = 'この電話番号のカスタマーサービスは既に存在します' WHERE `type_id` = 6 AND `code` = '400258';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスアカウントは既に存在します' WHERE `type_id` = 6 AND `code` = '400259';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービス担当者を追加しました' WHERE `type_id` = 6 AND `code` = '400260';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスの追加に失敗しました' WHERE `type_id` = 6 AND `code` = '400261';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービス名を空にすることはできません' WHERE `type_id` = 6 AND `code` = '400262';
UPDATE `eb_lang_code` SET `lang_explain` = '2回入力されたパスワードに一貫性がありません' WHERE `type_id` = 6 AND `code` = '400264';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーが存在しません。カスタマーサービスが強制的にログインを禁止します' WHERE `type_id` = 6 AND `code` = '400265';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインしたカスタマーサービスが存在しません' WHERE `type_id` = 6 AND `code` = '400266';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスプラットフォームに入る前に、カスタマーサービスアカウントとパスワードを入力してください' WHERE `type_id` = 6 AND `code` = '400267';
UPDATE `eb_lang_code` SET `lang_explain` = 'トークスクリプトを作成しました' WHERE `type_id` = 6 AND `code` = '400270';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストボックスの幅を入力してください' WHERE `type_id` = 6 AND `code` = '400277';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストボックスの正しい幅を入力してください' WHERE `type_id` = 6 AND `code` = '400278';
UPDATE `eb_lang_code` SET `lang_explain` = '複数行テキストボックスの幅を入力してください' WHERE `type_id` = 6 AND `code` = '400279';
UPDATE `eb_lang_code` SET `lang_explain` = '複数行テキストボックスの高さを入力してください' WHERE `type_id` = 6 AND `code` = '400280';
UPDATE `eb_lang_code` SET `lang_explain` = '複数行テキストボックスの正しい幅を入力してください' WHERE `type_id` = 6 AND `code` = '400281';
UPDATE `eb_lang_code` SET `lang_explain` = '複数行テキストボックスの正しい幅を入力してください' WHERE `type_id` = 6 AND `code` = '400282';
UPDATE `eb_lang_code` SET `lang_explain` = '第1および第2レベルのリベート率は100% を超えることはできません' WHERE `type_id` = 6 AND `code` = '400285';
UPDATE `eb_lang_code` SET `lang_explain` = '配布ポスターは5枚までです' WHERE `type_id` = 6 AND `code` = '400286';
UPDATE `eb_lang_code` SET `lang_explain` = '完全な配布の最小量は0より小さくすることはできません' WHERE `type_id` = 6 AND `code` = '400289';
UPDATE `eb_lang_code` SET `lang_explain` = '少なくとも1つのフィールドが存在します' WHERE `type_id` = 6 AND `code` = '400294';
UPDATE `eb_lang_code` SET `lang_explain` = 'データグループを追加しました' WHERE `type_id` = 6 AND `code` = '400295';
UPDATE `eb_lang_code` SET `lang_explain` = '4つ以下' WHERE `type_id` = 6 AND `code` = '400298';
UPDATE `eb_lang_code` SET `lang_explain` = 'チェックイン日の設定は7日を超えることはできません' WHERE `type_id` = 6 AND `code` = '400299';
UPDATE `eb_lang_code` SET `lang_explain` = '関連付けしました' WHERE `type_id` = 6 AND `code` = '400300';
UPDATE `eb_lang_code` SET `lang_explain` = 'データキャッシュを更新しました' WHERE `type_id` = 6 AND `code` = '400302';
UPDATE `eb_lang_code` SET `lang_explain` = 'データキャッシュの更新に失敗しました' WHERE `type_id` = 6 AND `code` = '400303';
UPDATE `eb_lang_code` SET `lang_explain` = '置換しました' WHERE `type_id` = 6 AND `code` = '400306';
UPDATE `eb_lang_code` SET `lang_explain` = 'バックアップファイルが破損している可能性があります。確認してください' WHERE `type_id` = 6 AND `code` = '400308';
UPDATE `eb_lang_code` SET `lang_explain` = 'カードを生成しました' WHERE `type_id` = 6 AND `code` = '400313';
UPDATE `eb_lang_code` SET `lang_explain` = 'メッセージキューに正常に参加しました' WHERE `type_id` = 6 AND `code` = '400318';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログアウトしました' WHERE `type_id` = 6 AND `code` = '400319';
UPDATE `eb_lang_code` SET `lang_explain` = 'メンバーラベルを空にすることはできません' WHERE `type_id` = 6 AND `code` = '400322';
UPDATE `eb_lang_code` SET `lang_explain` = 'レベルアイコンをアップロードしてください' WHERE `type_id` = 6 AND `code` = '400327';
UPDATE `eb_lang_code` SET `lang_explain` = '認証は成功しましたが、データベースへの書き込みに失敗しました。データベースリンクの設定を確認してください' WHERE `type_id` = 6 AND `code` = '400330';
UPDATE `eb_lang_code` SET `lang_explain` = '認可申請に成功しました' WHERE `type_id` = 6 AND `code` = '400335';
UPDATE `eb_lang_code` SET `lang_explain` = '検証コードエラー' WHERE `type_id` = 6 AND `code` = '400336';
UPDATE `eb_lang_code` SET `lang_explain` = '生放送の価格は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400341';
UPDATE `eb_lang_code` SET `lang_explain` = '購入数量制限は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400355';
UPDATE `eb_lang_code` SET `lang_explain` = 'スラッシュの数は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400357';
UPDATE `eb_lang_code` SET `lang_explain` = '交渉する人の数は1より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400359';
UPDATE `eb_lang_code` SET `lang_explain` = '商品詳細を入力してください' WHERE `type_id` = 6 AND `code` = '400361';
UPDATE `eb_lang_code` SET `lang_explain` = '仮想参加人数は成立人数を超えることはできません' WHERE `type_id` = 6 AND `code` = '400364';
UPDATE `eb_lang_code` SET `lang_explain` = '仮想参加人数は成立人数を超えることはできません' WHERE `type_id` = 6 AND `code` = '400365';
UPDATE `eb_lang_code` SET `lang_explain` = '単一の購入数量は0より大きくなければなりません' WHERE `type_id` = 6 AND `code` = '400367';
UPDATE `eb_lang_code` SET `lang_explain` = 'グループ内の人数を2人未満にすることはできません' WHERE `type_id` = 6 AND `code` = '400369';
UPDATE `eb_lang_code` SET `lang_explain` = 'グループの有効期間は0より大きい必要があります' WHERE `type_id` = 6 AND `code` = '400371';
UPDATE `eb_lang_code` SET `lang_explain` = 'クーポン金額を入力してください' WHERE `type_id` = 6 AND `code` = '400374';
UPDATE `eb_lang_code` SET `lang_explain` = 'クーポンの最低利用金額を入力してください' WHERE `type_id` = 6 AND `code` = '400375';
UPDATE `eb_lang_code` SET `lang_explain` = 'クーポンの有効期限を入力してください' WHERE `type_id` = 6 AND `code` = '400376';
UPDATE `eb_lang_code` SET `lang_explain` = 'ピックアップポイントの大きな画像を選択してください' WHERE `type_id` = 6 AND `code` = '400382';
UPDATE `eb_lang_code` SET `lang_explain` = 'ボーナスポイントは数字でなければなりません' WHERE `type_id` = 6 AND `code` = '400398';
UPDATE `eb_lang_code` SET `lang_explain` = '会社を追加しました' WHERE `type_id` = 6 AND `code` = '400401';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイル画像のサイズ(高さ)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400405';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルの大きな画像サイズ(高さ)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400406';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイル画像のサイズ(幅)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400407';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイル画像のサイズ(幅)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400408';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルの画像のサイズ(高さ)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400409';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルの画像のサイズ(高さ)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400410';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルの画像のサイズ(幅)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400411';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルの画像のサイズ(幅)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400412';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルのサイズ(高さ)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400413';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルのサイズ(高さ)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400414';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルのサイズ(幅)は数値でなければなりません' WHERE `type_id` = 6 AND `code` = '400415';
UPDATE `eb_lang_code` SET `lang_explain` = 'サムネイルのサイズ(幅)は0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400416';
UPDATE `eb_lang_code` SET `lang_explain` = 'ウォーターマークテキストの長さは1～10桁です' WHERE `type_id` = 6 AND `code` = '400418';
UPDATE `eb_lang_code` SET `lang_explain` = '透かしテキストのサイズは0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400420';
UPDATE `eb_lang_code` SET `lang_explain` = 'ウォーターマークの横座標のオフセットは0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400422';
UPDATE `eb_lang_code` SET `lang_explain` = '透かし縦オフセットは0以上でなければなりません' WHERE `type_id` = 6 AND `code` = '400424';
UPDATE `eb_lang_code` SET `lang_explain` = '審査の承認または却下' WHERE `type_id` = 6 AND `code` = '400430';
UPDATE `eb_lang_code` SET `lang_explain` = '放送時間は現在時刻の10分後にする必要があり、開始時刻を6か月後にすることはできません' WHERE `type_id` = 6 AND `code` = '400433';
UPDATE `eb_lang_code` SET `lang_explain` = '放送時間と終了時間の間の間隔は30分より短くしてはならず、24時間を超えてはならない' WHERE `type_id` = 6 AND `code` = '400434';
UPDATE `eb_lang_code` SET `lang_explain` = '正しいライブ配信商品を選択してください' WHERE `type_id` = 6 AND `code` = '400436';
UPDATE `eb_lang_code` SET `lang_explain` = 'ライブルームのステータスが正しくありません' WHERE `type_id` = 6 AND `code` = '400437';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取り済みです' WHERE `type_id` = 6 AND `code` = '400441';
UPDATE `eb_lang_code` SET `lang_explain` = '同じタイプの低レベルタスクの制限数より少なくすることはできません' WHERE `type_id` = 6 AND `code` = '400445';
UPDATE `eb_lang_code` SET `lang_explain` = '同じタイプの高レベルタスクの制限数よりも大きくすることはできません' WHERE `type_id` = 6 AND `code` = '400446';
UPDATE `eb_lang_code` SET `lang_explain` = 'パーソナルセンターテンプレートが存在しません' WHERE `type_id` = 6 AND `code` = '400459';
UPDATE `eb_lang_code` SET `lang_explain` = '同じ携帯番号の配達担当者は1人しか追加できません' WHERE `type_id` = 6 AND `code` = '400468';
UPDATE `eb_lang_code` SET `lang_explain` = '検証注文は発送できません' WHERE `type_id` = 6 AND `code` = '400473';
UPDATE `eb_lang_code` SET `lang_explain` = '注文にはアフターセールスアプリケーションがあります。最初に処理してください' WHERE `type_id` = 6 AND `code` = '400475';
UPDATE `eb_lang_code` SET `lang_explain` = 'ポイントとクーポンの返却に失敗しました' WHERE `type_id` = 6 AND `code` = '400489';
UPDATE `eb_lang_code` SET `lang_explain` = 'ロールバックポイントの増加に失敗しました' WHERE `type_id` = 6 AND `code` = '400494';
UPDATE `eb_lang_code` SET `lang_explain` = 'ラッキードローの名前を追加してください' WHERE `type_id` = 6 AND `code` = '400501';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選の説明などの文言を追加してください' WHERE `type_id` = 6 AND `code` = '400502';
UPDATE `eb_lang_code` SET `lang_explain` = 'クーポンを追加しました' WHERE `type_id` = 6 AND `code` = '400509';
UPDATE `eb_lang_code` SET `lang_explain` = 'クーポンを発行しました' WHERE `type_id` = 6 AND `code` = '400510';
UPDATE `eb_lang_code` SET `lang_explain` = '交渉する人の数は{:num}を超えることはできません' WHERE `type_id` = 6 AND `code` = '400512';
UPDATE `eb_lang_code` SET `lang_explain` = '注文ステータスエラー' WHERE `type_id` = 6 AND `code` = '400530';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選イベントの追加に失敗しました' WHERE `type_id` = 6 AND `code` = '400536';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選は存在しません' WHERE `type_id` = 6 AND `code` = '400537';
UPDATE `eb_lang_code` SET `lang_explain` = 'プロトコルタイプがありません' WHERE `type_id` = 6 AND `code` = '400548';
UPDATE `eb_lang_code` SET `lang_explain` = '最初にインターフェイスキーを設定してください' WHERE `type_id` = 6 AND `code` = '400554';
UPDATE `eb_lang_code` SET `lang_explain` = 'フォルダを作成できません。アップロードディレクトリの権限を確認してください' WHERE `type_id` = 6 AND `code` = '400555';
UPDATE `eb_lang_code` SET `lang_explain` = 'フォーマットエラー' WHERE `type_id` = 6 AND `code` = '400558';
UPDATE `eb_lang_code` SET `lang_explain` = '購入制限は1未満にすることはできません' WHERE `type_id` = 6 AND `code` = '400571';
UPDATE `eb_lang_code` SET `lang_explain` = '第1レベルと第2レベルのリベートの合計は、製品の価格を超えることはできません' WHERE `type_id` = 6 AND `code` = '400572';
UPDATE `eb_lang_code` SET `lang_explain` = '{:name}仕様が存在しません' WHERE `type_id` = 6 AND `code` = '400582';
UPDATE `eb_lang_code` SET `lang_explain` = '{:name}属性が存在しません' WHERE `type_id` = 6 AND `code` = '400583';
UPDATE `eb_lang_code` SET `lang_explain` = '少なくとも1つの属性を設定してください' WHERE `type_id` = 6 AND `code` = '400584';
UPDATE `eb_lang_code` SET `lang_explain` = 'タイムセールへの商品参加が有効になっています。この操作は実行できません' WHERE `type_id` = 6 AND `code` = '400585';
UPDATE `eb_lang_code` SET `lang_explain` = 'メンバー価格を0にすることはできません' WHERE `type_id` = 6 AND `code` = '400588';
UPDATE `eb_lang_code` SET `lang_explain` = 'カード番号: {:key}パスワード: {:value}、追加されました。もう一度カードキーを追加してください' WHERE `type_id` = 6 AND `code` = '400590';
UPDATE `eb_lang_code` SET `lang_explain` = '元のパスワードエラー' WHERE `type_id` = 6 AND `code` = '400597';
UPDATE `eb_lang_code` SET `lang_explain` = '{:name}デフォルト値を入力してください' WHERE `type_id` = 6 AND `code` = '400604';
UPDATE `eb_lang_code` SET `lang_explain` = '{:name}正しい URL を入力してください' WHERE `type_id` = 6 AND `code` = '400605';
UPDATE `eb_lang_code` SET `lang_explain` = '{:name}を空にすることはできません' WHERE `type_id` = 6 AND `code` = '400607';
UPDATE `eb_lang_code` SET `lang_explain` = '削除されたクラウドストレージは存在しません' WHERE `type_id` = 6 AND `code` = '400608';
UPDATE `eb_lang_code` SET `lang_explain` = 'クラウドストレージは使用中です。他のスペースを削除するには、アクティブ化する必要があります' WHERE `type_id` = 6 AND `code` = '400609';
UPDATE `eb_lang_code` SET `lang_explain` = 'クラウドスペース名を繰り返すことはできません' WHERE `type_id` = 6 AND `code` = '400610';
UPDATE `eb_lang_code` SET `lang_explain` = '一度に生成されるカードの最大数は6000を超えてはならない' WHERE `type_id` = 6 AND `code` = '400617';
UPDATE `eb_lang_code` SET `lang_explain` = 'リターンポイントの倍数を負にすることはできません' WHERE `type_id` = 6 AND `code` = '400634';
UPDATE `eb_lang_code` SET `lang_explain` = 'サインインポイントの倍数を負にすることはできません' WHERE `type_id` = 6 AND `code` = '400638';
UPDATE `eb_lang_code` SET `lang_explain` = '有効期間(日数)を入力してください' WHERE `type_id` = 6 AND `code` = '400643';
UPDATE `eb_lang_code` SET `lang_explain` = '有効期間(日)を負にすることはできません' WHERE `type_id` = 6 AND `code` = '400644';
UPDATE `eb_lang_code` SET `lang_explain` = '元のデフォルトアドレスのキャンセルに失敗しました' WHERE `type_id` = 6 AND `code` = '400649';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインの有効期限が切れています。再度ログインしてください' WHERE `type_id` = 6 AND `code` = '400654';
UPDATE `eb_lang_code` SET `lang_explain` = '引き出し額は{:money}元未満にはできません' WHERE `type_id` = 6 AND `code` = '400662';
UPDATE `eb_lang_code` SET `lang_explain` = '出金手数料が足りない{:money}元' WHERE `type_id` = 6 AND `code` = '400663';
UPDATE `eb_lang_code` SET `lang_explain` = '出金手数料が0より大きい' WHERE `type_id` = 6 AND `code` = '400664';
UPDATE `eb_lang_code` SET `lang_explain` = '最小額を変更するためのエンタープライズ WeChat 支払いは1元です' WHERE `type_id` = 6 AND `code` = '400665';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーラベルのクリアに失敗しました' WHERE `type_id` = 6 AND `code` = '400667';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーレベルの経験値は、前のレベルで設定された経験値より高くなければなりません' WHERE `type_id` = 6 AND `code` = '400673';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーレベルの経験値は、次のレベルで設定された経験値よりも低くなければなりません' WHERE `type_id` = 6 AND `code` = '400674';
UPDATE `eb_lang_code` SET `lang_explain` = '設定したユーザーレベルが検出されました。このレベルを繰り返すことはできません' WHERE `type_id` = 6 AND `code` = '400675';
UPDATE `eb_lang_code` SET `lang_explain` = 'このユーザーレベルの経験値を設定したことが検出されました。経験値を繰り返すことはできません' WHERE `type_id` = 6 AND `code` = '400676';
UPDATE `eb_lang_code` SET `lang_explain` = '紹介人数の加算に失敗しました' WHERE `type_id` = 6 AND `code` = '400686';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインタイプの設定に失敗しました' WHERE `type_id` = 6 AND `code` = '400687';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーポイントの増加に失敗しました' WHERE `type_id` = 6 AND `code` = '400692';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーポイントの削減に失敗しました' WHERE `type_id` = 6 AND `code` = '400693';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーエクスペリエンスの向上に失敗しました' WHERE `type_id` = 6 AND `code` = '400694';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーエクスペリエンスの低下に失敗しました' WHERE `type_id` = 6 AND `code` = '400695';
UPDATE `eb_lang_code` SET `lang_explain` = 'このユーザーはすでにこのユーザーレベルを持っているため、再度付与することはできません' WHERE `type_id` = 6 AND `code` = '400700';
UPDATE `eb_lang_code` SET `lang_explain` = 'ギフト日数を0にすることはできません' WHERE `type_id` = 6 AND `code` = '400701';
UPDATE `eb_lang_code` SET `lang_explain` = 'あなたの IP はホワイトリストにありません。Tencent WeChat パブリックプラットフォームに移動して、IP をホワイトリストに追加してください' WHERE `type_id` = 6 AND `code` = '400704';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストメッセージを選択してください' WHERE `type_id` = 6 AND `code` = '400709';
UPDATE `eb_lang_code` SET `lang_explain` = 'クラウドプリンター番号がありません' WHERE `type_id` = 6 AND `code` = '400716';
UPDATE `eb_lang_code` SET `lang_explain` = '2レベルの分類のみをサポート' WHERE `type_id` = 6 AND `code` = '400740';
UPDATE `eb_lang_code` SET `lang_explain` = '同期バーの数は100を超えることはできません' WHERE `type_id` = 6 AND `code` = '400743';
UPDATE `eb_lang_code` SET `lang_explain` = 'カテゴリ名の長さは25文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '400746';
UPDATE `eb_lang_code` SET `lang_explain` = 'カテゴリアイコンの長さは128文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '400747';
UPDATE `eb_lang_code` SET `lang_explain` = '大きな分類画像の長さは200文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '400748';
UPDATE `eb_lang_code` SET `lang_explain` = '並べ替えは0未満にはできません' WHERE `type_id` = 6 AND `code` = '400750';
UPDATE `eb_lang_code` SET `lang_explain` = 'ステータスは0～1の整数でなければなりません' WHERE `type_id` = 6 AND `code` = '400751';
UPDATE `eb_lang_code` SET `lang_explain` = '権利と利益の紹介は8語より長くすることはできません' WHERE `type_id` = 6 AND `code` = '400752';
UPDATE `eb_lang_code` SET `lang_explain` = '表示名は6文字より長くすることはできません' WHERE `type_id` = 6 AND `code` = '400755';
UPDATE `eb_lang_code` SET `lang_explain` = 'プロモーションコミッションの単価を0未満にすることはできません' WHERE `type_id` = 6 AND `code` = '400756';
UPDATE `eb_lang_code` SET `lang_explain` = '毎日のプロモーションコミッションの上限は -1より小さくすることはできません' WHERE `type_id` = 6 AND `code` = '400757';
UPDATE `eb_lang_code` SET `lang_explain` = '説明の内容は120文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '400761';
UPDATE `eb_lang_code` SET `lang_explain` = 'アカウントのパスワードは6～32桁でなければなりません' WHERE `type_id` = 6 AND `code` = '400762';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインしました' WHERE `type_id` = 6 AND `code` = '410001';
UPDATE `eb_lang_code` SET `lang_explain` = '認証コードを送信しました' WHERE `type_id` = 6 AND `code` = '410007';
UPDATE `eb_lang_code` SET `lang_explain` = '検証コードエラー' WHERE `type_id` = 6 AND `code` = '410010';
UPDATE `eb_lang_code` SET `lang_explain` = 'パスワードは6～16桁でなければなりません' WHERE `type_id` = 6 AND `code` = '410011';
UPDATE `eb_lang_code` SET `lang_explain` = '登録しました' WHERE `type_id` = 6 AND `code` = '410013';
UPDATE `eb_lang_code` SET `lang_explain` = '連携しました' WHERE `type_id` = 6 AND `code` = '410016';
UPDATE `eb_lang_code` SET `lang_explain` = '認証に成功しました' WHERE `type_id` = 6 AND `code` = '410023';
UPDATE `eb_lang_code` SET `lang_explain` = '今日送信したテキストメッセージの数が上限に達しました' WHERE `type_id` = 6 AND `code` = '410029';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーログインに失敗しました。新しいユーザーを生成できません。後でもう一度試してください' WHERE `type_id` = 6 AND `code` = '410034';
UPDATE `eb_lang_code` SET `lang_explain` = '新しいユーザーログインタイプの変更中にエラーが発生しました' WHERE `type_id` = 6 AND `code` = '410036';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーアクセストークンの取得に失敗しました' WHERE `type_id` = 6 AND `code` = '410038';
UPDATE `eb_lang_code` SET `lang_explain` = 'H5の既存のアカウントがこのアカウントにバインドされているかどうか' WHERE `type_id` = 6 AND `code` = '410041';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取り済みです' WHERE `type_id` = 6 AND `code` = '410051';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選の記録がありません' WHERE `type_id` = 6 AND `code` = '410054';
UPDATE `eb_lang_code` SET `lang_explain` = '商品購入後、より多くの抽選を獲得' WHERE `type_id` = 6 AND `code` = '410063';
UPDATE `eb_lang_code` SET `lang_explain` = 'より多くの友達を招待して、ラッキードローの数を獲得' WHERE `type_id` = 6 AND `code` = '410065';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選でユーザーポイントを差し引くことができませんでした' WHERE `type_id` = 6 AND `code` = '410066';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選に失敗しました。残高不足です' WHERE `type_id` = 6 AND `code` = '410067';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選でユーザーの残高を差し引くことができませんでした' WHERE `type_id` = 6 AND `code` = '410068';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選で、ユーザーが抽選に当選した回数を差し引くことができませんでした' WHERE `type_id` = 6 AND `code` = '410069';
UPDATE `eb_lang_code` SET `lang_explain` = '賞品の総数を減らす抽選に失敗しました' WHERE `type_id` = 6 AND `code` = '410070';
UPDATE `eb_lang_code` SET `lang_explain` = 'セッションキーの取得に失敗しました' WHERE `type_id` = 6 AND `code` = '410077';
UPDATE `eb_lang_code` SET `lang_explain` = 'トークン{:msg}の取得に失敗しました' WHERE `type_id` = 6 AND `code` = '410085';
UPDATE `eb_lang_code` SET `lang_explain` = 'プラットフォームエラー: 例外が発生しました。後で再試行してください' WHERE `type_id` = 6 AND `code` = '410087';
UPDATE `eb_lang_code` SET `lang_explain` = '企業から個人ウォレットへの送金の開始に失敗しました' WHERE `type_id` = 6 AND `code` = '410089';
UPDATE `eb_lang_code` SET `lang_explain` = 'トークンが無効なため、ユーザーのチャット履歴を取得できません' WHERE `type_id` = 6 AND `code` = '410090';
UPDATE `eb_lang_code` SET `lang_explain` = '画像をアップロードしました' WHERE `type_id` = 6 AND `code` = '410091';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザー uid は現在のチャットユーザーの範囲外です' WHERE `type_id` = 6 AND `code` = '410092';
UPDATE `eb_lang_code` SET `lang_explain` = 'バックグラウンドのアフターオーダーリスト処理に移動してください' WHERE `type_id` = 6 AND `code` = '410094';
UPDATE `eb_lang_code` SET `lang_explain` = '転送しました' WHERE `type_id` = 6 AND `code` = '410099';
UPDATE `eb_lang_code` SET `lang_explain` = 'トピックタイトルの内容を空にすることはできません' WHERE `type_id` = 6 AND `code` = '410102';
UPDATE `eb_lang_code` SET `lang_explain` = 'タイトルの長さは50文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '410106';
UPDATE `eb_lang_code` SET `lang_explain` = 'スピーチの長さは500語を超えることはできません' WHERE `type_id` = 6 AND `code` = '410110';
UPDATE `eb_lang_code` SET `lang_explain` = 'Wechat の最低引き出し額は1元未満にすることはできません' WHERE `type_id` = 6 AND `code` = '410112';
UPDATE `eb_lang_code` SET `lang_explain` = 'リチャージ額を0元にすることはできません' WHERE `type_id` = 6 AND `code` = '410122';
UPDATE `eb_lang_code` SET `lang_explain` = 'リチャージ額を{:money}未満にすることはできません' WHERE `type_id` = 6 AND `code` = '410124';
UPDATE `eb_lang_code` SET `lang_explain` = 'チャージしました' WHERE `type_id` = 6 AND `code` = '410125';
UPDATE `eb_lang_code` SET `lang_explain` = 'サインインして{:integral}ポイントを獲得' WHERE `type_id` = 6 AND `code` = '410127';
UPDATE `eb_lang_code` SET `lang_explain` = 'お気に入りに登録しました' WHERE `type_id` = 6 AND `code` = '410129';
UPDATE `eb_lang_code` SET `lang_explain` = 'お気に入り登録に失敗しました' WHERE `type_id` = 6 AND `code` = '410130';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログアウトしました' WHERE `type_id` = 6 AND `code` = '410135';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービススタッフがオンラインにいません。後でご連絡ください' WHERE `type_id` = 6 AND `code` = '410136';
UPDATE `eb_lang_code` SET `lang_explain` = 'あなたはカスタマーサービスではないため、ログインできません' WHERE `type_id` = 6 AND `code` = '410138';
UPDATE `eb_lang_code` SET `lang_explain` = '請求書のヘッダー(請求書を発行した会社の名前)を正しく入力してください' WHERE `type_id` = 6 AND `code` = '410146';
UPDATE `eb_lang_code` SET `lang_explain` = '名前は25文字を超えることはできません' WHERE `type_id` = 6 AND `code` = '410156';
UPDATE `eb_lang_code` SET `lang_explain` = '有効化しました' WHERE `type_id` = 6 AND `code` = '410165';
UPDATE `eb_lang_code` SET `lang_explain` = 'フォントファイル Bold がありません' WHERE `type_id` = 6 AND `code` = '410168';
UPDATE `eb_lang_code` SET `lang_explain` = '不足しているフォントファイル Normal' WHERE `type_id` = 6 AND `code` = '410169';
UPDATE `eb_lang_code` SET `lang_explain` = '画像の生成中にシステムエラーが発生しました' WHERE `type_id` = 6 AND `code` = '410171';
UPDATE `eb_lang_code` SET `lang_explain` = '実際の支払い額は0元未満にすることはできません' WHERE `type_id` = 6 AND `code` = '410176';
UPDATE `eb_lang_code` SET `lang_explain` = 'アフターサービス注文のステータスではこの操作を実行できません' WHERE `type_id` = 6 AND `code` = '410180';
UPDATE `eb_lang_code` SET `lang_explain` = '払い戻し変更ステータスエラー' WHERE `type_id` = 6 AND `code` = '410181';
UPDATE `eb_lang_code` SET `lang_explain` = '返金ステータスを変更しました' WHERE `type_id` = 6 AND `code` = '410182';
UPDATE `eb_lang_code` SET `lang_explain` = '返金しました' WHERE `type_id` = 6 AND `code` = '410186';
UPDATE `eb_lang_code` SET `lang_explain` = '検証コードを入力するか、検証QRコードをスキャンしてください' WHERE `type_id` = 6 AND `code` = '410188';
UPDATE `eb_lang_code` SET `lang_explain` = '検証しました' WHERE `type_id` = 6 AND `code` = '410189';
UPDATE `eb_lang_code` SET `lang_explain` = '支払額を0元にすることはできません' WHERE `type_id` = 6 AND `code` = '410191';
UPDATE `eb_lang_code` SET `lang_explain` = '注文を作成しました' WHERE `type_id` = 6 AND `code` = '410203';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取りを完了しました' WHERE `type_id` = 6 AND `code` = '410204';
UPDATE `eb_lang_code` SET `lang_explain` = '購入した在庫は十分ではありません{:cart_num}{:unit_name}' WHERE `type_id` = 6 AND `code` = '410214';
UPDATE `eb_lang_code` SET `lang_explain` = '支払いが完了しました' WHERE `type_id` = 6 AND `code` = '410217';
UPDATE `eb_lang_code` SET `lang_explain` = 'ビジネスサービスを評価してください' WHERE `type_id` = 6 AND `code` = '410221';
UPDATE `eb_lang_code` SET `lang_explain` = '再選択しました' WHERE `type_id` = 6 AND `code` = '410225';
UPDATE `eb_lang_code` SET `lang_explain` = 'ポイントによる割引の適用に失敗しました' WHERE `type_id` = 6 AND `code` = '410227';
UPDATE `eb_lang_code` SET `lang_explain` = 'メンバータイプが存在しません' WHERE `type_id` = 6 AND `code` = '410228';
UPDATE `eb_lang_code` SET `lang_explain` = 'ショッピングカートの情報を取得できませんでした' WHERE `type_id` = 6 AND `code` = '410233';
UPDATE `eb_lang_code` SET `lang_explain` = '1回の購入数量は{:limit}個を超えることはできません' WHERE `type_id` = 6 AND `code` = '410239';
UPDATE `eb_lang_code` SET `lang_explain` = 'この商品は{:limit}個に限定されています。すでに{:pay_num}個を購入しています' WHERE `type_id` = 6 AND `code` = '410240';
UPDATE `eb_lang_code` SET `lang_explain` = '注文ステータスエラー' WHERE `type_id` = 6 AND `code` = '410266';
UPDATE `eb_lang_code` SET `lang_explain` = 'この注文は検証できません' WHERE `type_id` = 6 AND `code` = '410267';
UPDATE `eb_lang_code` SET `lang_explain` = '注文にはアフターセールスアプリケーションがあります。最初に処理してください' WHERE `type_id` = 6 AND `code` = '410268';
UPDATE `eb_lang_code` SET `lang_explain` = '注文は検証されました' WHERE `type_id` = 6 AND `code` = '410270';
UPDATE `eb_lang_code` SET `lang_explain` = 'グループ注文はまだ正常に検証されていません' WHERE `type_id` = 6 AND `code` = '410271';
UPDATE `eb_lang_code` SET `lang_explain` = '発送しました' WHERE `type_id` = 6 AND `code` = '410273';
UPDATE `eb_lang_code` SET `lang_explain` = 'このユーザーがいないと、アップグレードユーザーレベルを検出できません' WHERE `type_id` = 6 AND `code` = '410284';
UPDATE `eb_lang_code` SET `lang_explain` = '日数を0にすることはできません' WHERE `type_id` = 6 AND `code` = '410289';
UPDATE `eb_lang_code` SET `lang_explain` = 'チェックインデータの追加に失敗しました' WHERE `type_id` = 6 AND `code` = '410290';
UPDATE `eb_lang_code` SET `lang_explain` = 'この製品{:num}の在庫が不足しています' WHERE `type_id` = 6 AND `code` = '410297';
UPDATE `eb_lang_code` SET `lang_explain` = 'お一人様合計{:num}個まで' WHERE `type_id` = 6 AND `code` = '410298';
UPDATE `eb_lang_code` SET `lang_explain` = '値下げ交渉が成立しませんでした' WHERE `type_id` = 6 AND `code` = '410308';
UPDATE `eb_lang_code` SET `lang_explain` = '各注文は{:num}個に制限されています' WHERE `type_id` = 6 AND `code` = '410313';
UPDATE `eb_lang_code` SET `lang_explain` = 'お一人様{:num}個までに制限されています' WHERE `type_id` = 6 AND `code` = '410317';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選は存在しません' WHERE `type_id` = 6 AND `code` = '410318';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取りました' WHERE `type_id` = 6 AND `code` = '410319';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChat API の1日の上限に達しました' WHERE `type_id` = 6 AND `code` = '45009';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストメッセージが制限を超えています' WHERE `type_id` = 6 AND `code` = '45008';
UPDATE `eb_lang_code` SET `lang_explain` = '画像リンクフィールドが制限を超えています' WHERE `type_id` = 6 AND `code` = '45006';
UPDATE `eb_lang_code` SET `lang_explain` = 'リンクフィールドが制限を超えています' WHERE `type_id` = 6 AND `code` = '45005';
UPDATE `eb_lang_code` SET `lang_explain` = 'タイトルフィールドが制限を超えています' WHERE `type_id` = 6 AND `code` = '45003';
UPDATE `eb_lang_code` SET `lang_explain` = 'マルチメディアファイルのサイズが制限を超えています' WHERE `type_id` = 6 AND `code` = '45001';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストメッセージの内容が空です' WHERE `type_id` = 6 AND `code` = '44004';
UPDATE `eb_lang_code` SET `lang_explain` = 'テキストメッセージの内容が空です' WHERE `type_id` = 6 AND `code` = '44003';
UPDATE `eb_lang_code` SET `lang_explain` = 'POST データパケットが空です' WHERE `type_id` = 6 AND `code` = '44002';
UPDATE `eb_lang_code` SET `lang_explain` = 'マルチメディアファイルが空です' WHERE `type_id` = 6 AND `code` = '44001';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューデータがありません' WHERE `type_id` = 6 AND `code` = '41007';
UPDATE `eb_lang_code` SET `lang_explain` = 'マルチメディアファイルデータがありません' WHERE `type_id` = 6 AND `code` = '41005';
UPDATE `eb_lang_code` SET `lang_explain` = 'シークレットパラメータがありません' WHERE `type_id` = 6 AND `code` = '41004';
UPDATE `eb_lang_code` SET `lang_explain` = 'ボタンタイプエラー' WHERE `type_id` = 6 AND `code` = '40119';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なカスタムメニューユーザー' WHERE `type_id` = 6 AND `code` = '40028';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューボタンの URL の長さが不正です' WHERE `type_id` = 6 AND `code` = '40027';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューボタンのキーの長さが不正です' WHERE `type_id` = 6 AND `code` = '40026';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューボタン名の長さが不正です' WHERE `type_id` = 6 AND `code` = '40025';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューボタンの種類が正しくありません' WHERE `type_id` = 6 AND `code` = '40024';
UPDATE `eb_lang_code` SET `lang_explain` = 'サブメニューボタンの数が不正です' WHERE `type_id` = 6 AND `code` = '40023';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なサブメニューレベル' WHERE `type_id` = 6 AND `code` = '40022';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なボタンタイプ' WHERE `type_id` = 6 AND `code` = '40017';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なメニュータイプ' WHERE `type_id` = 6 AND `code` = '40015';
UPDATE `eb_lang_code` SET `lang_explain` = '不正な access_token です。access_token の有効性(有効期限が切れているかどうかなど)を慎重に比較するか、適切な公式アカウントに対してインターフェイスが呼び出されているかどうかを確認してください' WHERE `type_id` = 6 AND `code` = '40014';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なメッセージタイプ' WHERE `type_id` = 6 AND `code` = '40008';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なメディアファイル ID' WHERE `type_id` = 6 AND `code` = '40007';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なファイルサイズ' WHERE `type_id` = 6 AND `code` = '40006';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なファイルタイプ' WHERE `type_id` = 6 AND `code` = '40005';
UPDATE `eb_lang_code` SET `lang_explain` = '不正なメディアファイルタイプ' WHERE `type_id` = 6 AND `code` = '40004';
UPDATE `eb_lang_code` SET `lang_explain` = '不正な OpenID です。OpenID (ユーザー)が公式アカウントをフォローしているかどうか、または他の公式アカウントの OpenID であるかどうかを確認してください' WHERE `type_id` = 6 AND `code` = '40003';
UPDATE `eb_lang_code` SET `lang_explain` = '個人用テンプレートの数が上限に達しました。上限は25です' WHERE `type_id` = 6 AND `code` = '200012';
UPDATE `eb_lang_code` SET `lang_explain` = '日以内に利用可能' WHERE `type_id` = 6 AND `code` = '天内可用';
UPDATE `eb_lang_code` SET `lang_explain` = '引き上げてさらに読み込む' WHERE `type_id` = 6 AND `code` = '上拉加载更多';
UPDATE `eb_lang_code` SET `lang_explain` = '支払いが完了しました' WHERE `type_id` = 6 AND `code` = '支付成功';
UPDATE `eb_lang_code` SET `lang_explain` = '日' WHERE `type_id` = 6 AND `code` = '天';
UPDATE `eb_lang_code` SET `lang_explain` = '時' WHERE `type_id` = 6 AND `code` = '时';
UPDATE `eb_lang_code` SET `lang_explain` = '分' WHERE `type_id` = 6 AND `code` = '分';
UPDATE `eb_lang_code` SET `lang_explain` = '秒' WHERE `type_id` = 6 AND `code` = '秒';
UPDATE `eb_lang_code` SET `lang_explain` = 'イベントは終了しました' WHERE `type_id` = 6 AND `code` = '活动已结束';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChat友達' WHERE `type_id` = 6 AND `code` = '微信好友';
UPDATE `eb_lang_code` SET `lang_explain` = '保存しました' WHERE `type_id` = 6 AND `code` = '保存成功';
UPDATE `eb_lang_code` SET `lang_explain` = '参考価格' WHERE `type_id` = 6 AND `code` = '划线价';
UPDATE `eb_lang_code` SET `lang_explain` = '`スーパーメンバー` をオフにする' WHERE `type_id` = 6 AND `code` = '开通“超级会员”立省';
UPDATE `eb_lang_code` SET `lang_explain` = '以内に発送' WHERE `type_id` = 6 AND `code` = '预售结束后';
UPDATE `eb_lang_code` SET `lang_explain` = 'SF Express の追跡番号を入力してください: 受信者または送信者の携帯電話番号の下4桁' WHERE `type_id` = 6 AND `code` = '顺丰请输入单号 :收件人或寄件人手机号后四位';
UPDATE `eb_lang_code` SET `lang_explain` = '過去7日間' WHERE `type_id` = 6 AND `code` = '最近7天';
UPDATE `eb_lang_code` SET `lang_explain` = '最大10枚の画像をアップロードでき、画像形式は JPG、PNG、JPEG をサポートしています' WHERE `type_id` = 6 AND `code` = '图片最多可上传10张,图片格式支持JPG、PNG、JPEG';
UPDATE `eb_lang_code` SET `lang_explain` = '日.' WHERE `type_id` = 6 AND `code` = '天.';
UPDATE `eb_lang_code` SET `lang_explain` = '0元トライアルの開始に成功しました' WHERE `type_id` = 6 AND `code` = '成功开启0元试用';
UPDATE `eb_lang_code` SET `lang_explain` = '連携しました' WHERE `type_id` = 6 AND `code` = '绑定成功';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスはオフラインです' WHERE `type_id` = 6 AND `code` = '商城客服已离线';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスが接続中' WHERE `type_id` = 6 AND `code` = '客服连接中';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスがオフラインです。フィードバックが必要ですか?' WHERE `type_id` = 6 AND `code` = '客服已下线，是否需要反馈？';
UPDATE `eb_lang_code` SET `lang_explain` = '企業' WHERE `type_id` = 6 AND `code` = '企业';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選' WHERE `type_id` = 6 AND `code` = '抽奖';
UPDATE `eb_lang_code` SET `lang_explain` = '追加しました' WHERE `type_id` = 6 AND `code` = '添加成功';
UPDATE `eb_lang_code` SET `lang_explain` = '受け取りました' WHERE `type_id` = 6 AND `code` = '领取成功';
UPDATE `eb_lang_code` SET `lang_explain` = '100語以内のコメント' WHERE `type_id` = 6 AND `code` = '填写备注信息，100字以内';
UPDATE `eb_lang_code` SET `lang_explain` = '申請しました' WHERE `type_id` = 6 AND `code` = '申请成功';
UPDATE `eb_lang_code` SET `lang_explain` = 'アクティビティルール' WHERE `type_id` = 6 AND `code` = '活动规则';
UPDATE `eb_lang_code` SET `lang_explain` = '注文を作成しました' WHERE `type_id` = 6 AND `code` = '订单创建成功';
UPDATE `eb_lang_code` SET `lang_explain` = '検証情報' WHERE `type_id` = 6 AND `code` = '核销信息';
UPDATE `eb_lang_code` SET `lang_explain` = '代理支払い合計' WHERE `type_id` = 6 AND `code` = '总代付';
UPDATE `eb_lang_code` SET `lang_explain` = '今すぐ支払う' WHERE `type_id` = 6 AND `code` = '立即付款';
UPDATE `eb_lang_code` SET `lang_explain` = '操作が完了しました' WHERE `type_id` = 6 AND `code` = '操作成功';
UPDATE `eb_lang_code` SET `lang_explain` = '削除しました' WHERE `type_id` = 6 AND `code` = '删除成功';
UPDATE `eb_lang_code` SET `lang_explain` = '最大3回のアップロード' WHERE `type_id` = 6 AND `code` = '最多可上传3张';
UPDATE `eb_lang_code` SET `lang_explain` = '時間制限タイムセール' WHERE `type_id` = 6 AND `code` = '限时秒杀';
UPDATE `eb_lang_code` SET `lang_explain` = 'グループモジュール、データがまだありません' WHERE `type_id` = 6 AND `code` = '拼团模块，暂无数据';
UPDATE `eb_lang_code` SET `lang_explain` = '利用可能' WHERE `type_id` = 6 AND `code` = '可用';
UPDATE `eb_lang_code` SET `lang_explain` = 'プロモーションアイテム、一時的にデータがありません' WHERE `type_id` = 6 AND `code` = '促销单品，暂无数据';
UPDATE `eb_lang_code` SET `lang_explain` = 'サービス契約とプライバシーポリシー' WHERE `type_id` = 6 AND `code` = '服务协议与隐私政策';
UPDATE `eb_lang_code` SET `lang_explain` = 'サービス契約とプライバシーポリシーの条項を注意深く読み、完全に理解してください。これには、インスタントメッセージング、コンテンツ共有、およびその他のサービスを提供するために、デバイスを収集する必要があります。情報、操作ログ、その他の個人情報。個人情報を表示、変更、削除し、[設定]で承認を管理できます。' WHERE `type_id` = 6 AND `code` = '请务必审慎阅读、充分理解“服务协议与 隐私政策”各条款，包括但不限于：为了 向你提供即时通讯、内容分享等服务，我 们需要收集你的设备信息、操作日志等个 人信息。你可以在“设置”中查看、变更、删除个人信息并管理你的授权。';
UPDATE `eb_lang_code` SET `lang_explain` = 'もっと詳しく。同意する場合は、[同意する]をクリックして、サービスの受け入れを開始してください。' WHERE `type_id` = 6 AND `code` = '了解详细信息。如你同意，请点击“我同意”开始接受我们的服务。';
UPDATE `eb_lang_code` SET `lang_explain` = 'さらにプルダウンロード' WHERE `type_id` = 6 AND `code` = '下拉加载更多';
UPDATE `eb_lang_code` SET `lang_explain` = 'ショッピングカートが正常に追加されました' WHERE `type_id` = 6 AND `code` = '添加购物车成功';
UPDATE `eb_lang_code` SET `lang_explain` = '消去しました' WHERE `type_id` = 6 AND `code` = '清除成功';
UPDATE `eb_lang_code` SET `lang_explain` = '九公抽選' WHERE `type_id` = 6 AND `code` = '九宫格抽奖活动';
UPDATE `eb_lang_code` SET `lang_explain` = 'コメントを追加してください(150ワード以内)' WHERE `type_id` = 6 AND `code` = '请添加备注（150字以内）';
UPDATE `eb_lang_code` SET `lang_explain` = 'オンラインアリペイで支払う' WHERE `type_id` = 6 AND `code` = '使用线上支付宝支付';
UPDATE `eb_lang_code` SET `lang_explain` = '設定しました' WHERE `type_id` = 6 AND `code` = '设置成功';
UPDATE `eb_lang_code` SET `lang_explain` = '[URL をコピー]をクリックしてブラウザで開く' WHERE `type_id` = 6 AND `code` = '点击复制网址去浏览器中打开';
UPDATE `eb_lang_code` SET `lang_explain` = '支払い注文は存在しません。ページは2秒後に自動的に閉じます!' WHERE `type_id` = 6 AND `code` = '支付订单不存在，页面将在2秒后自动关闭！';
UPDATE `eb_lang_code` SET `lang_explain` = '支払い注文は存在しません。ページは2秒後に自動的に閉じます' WHERE `type_id` = 6 AND `code` = '支付订单不存在,页面将在2秒后自动关闭';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインしました' WHERE `type_id` = 6 AND `code` = '登录成功';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザーが[OK]をクリックしました' WHERE `type_id` = 6 AND `code` = '用户点击确定';
UPDATE `eb_lang_code` SET `lang_explain` = 'ログインに失敗しました' WHERE `type_id` = 6 AND `code` = '登录失败';
UPDATE `eb_lang_code` SET `lang_explain` = 'カスタマーサービスメッセージ' WHERE `type_id` = 6 AND `code` = '客服消息';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChatの友達に送る' WHERE `type_id` = 6 AND `code` = '发送给微信好友';
UPDATE `eb_lang_code` SET `lang_explain` = 'レベル1' WHERE `type_id` = 6 AND `code` = '一级';
UPDATE `eb_lang_code` SET `lang_explain` = 'レベル2' WHERE `type_id` = 6 AND `code` = '二级';
UPDATE `eb_lang_code` SET `lang_explain` = '承認をクリックして、カスタマーサービスワークベンチにログインしてください' WHERE `type_id` = 6 AND `code` = '点击授权登录您的客服工作台';
UPDATE `eb_lang_code` SET `lang_explain` = '変更しました' WHERE `type_id` = 6 AND `code` = '修改成功';
UPDATE `eb_lang_code` SET `lang_explain` = '[即時ログアウト]をクリックすると、ユーザーログアウト同意書に同意したことになります' WHERE `type_id` = 6 AND `code` = '点击【立即注销】即代表您已经同意《用户注销协议》';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChatアカウントを記入' WHERE `type_id` = 6 AND `code` = '请填写您的微信账号';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChat' WHERE `type_id` = 6 AND `code` = '微信';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChatに記入してください' WHERE `type_id` = 6 AND `code` = '请填写微信号';
UPDATE `eb_lang_code` SET `lang_explain` = '1レベルアップ' WHERE `type_id` = 6 AND `code` = '一级分佣上浮';
UPDATE `eb_lang_code` SET `lang_explain` = 'セカンダリフローティング' WHERE `type_id` = 6 AND `code` = '二级分佣上浮';
UPDATE `eb_lang_code` SET `lang_explain` = 'クイックアップグレードスキル' WHERE `type_id` = 6 AND `code` = '快速升级技巧';
UPDATE `eb_lang_code` SET `lang_explain` = '総資産(￥)' WHERE `type_id` = 6 AND `code` = '总资产(元)';
UPDATE `eb_lang_code` SET `lang_explain` = 'Co リチャージ(￥)' WHERE `type_id` = 6 AND `code` = '累计充值(元)';
UPDATE `eb_lang_code` SET `lang_explain` = 'Co 花(￥)' WHERE `type_id` = 6 AND `code` = '累计消费(元)';
UPDATE `eb_lang_code` SET `lang_explain` = '現在の制限時間2番目のキル' WHERE `type_id` = 6 AND `code` = '当前限时秒杀';
UPDATE `eb_lang_code` SET `lang_explain` = '進行中の最新の商品タイムセール' WHERE `type_id` = 6 AND `code` = '最新商品秒杀进行中';
UPDATE `eb_lang_code` SET `lang_explain` = '凍結中の報酬は' WHERE `type_id` = 6 AND `code` = '冻结佣金为';
UPDATE `eb_lang_code` SET `lang_explain` = '充電量を0にすることはできません' WHERE `type_id` = 6 AND `code` = '充值金额不能为0';
UPDATE `eb_lang_code` SET `lang_explain` = 'バインドアカウント' WHERE `type_id` = 6 AND `code` = '是否绑定账号';
UPDATE `eb_lang_code` SET `lang_explain` = '入力した2つのパスワードは矛盾しています!' WHERE `type_id` = 6 AND `code` = '两次输入的密码不一致！';
UPDATE `eb_lang_code` SET `lang_explain` = '7日目' WHERE `type_id` = 6 AND `code` = '第七天';
UPDATE `eb_lang_code` SET `lang_explain` = '2回連続のサインイン' WHERE `type_id` = 6 AND `code` = '据说连续签到第';
UPDATE `eb_lang_code` SET `lang_explain` = '今日サインインしました!' WHERE `type_id` = 6 AND `code` = '您今日已签到!';
UPDATE `eb_lang_code` SET `lang_explain` = 'エージェントアプリケーション' WHERE `type_id` = 6 AND `code` = '代理商申请';
UPDATE `eb_lang_code` SET `lang_explain` = 'モールでのお買い物で利用可能' WHERE `type_id` = 6 AND `code` = '商城购物可享';
UPDATE `eb_lang_code` SET `lang_explain` = '経験値/円' WHERE `type_id` = 6 AND `code` = '点经验/元';
UPDATE `eb_lang_code` SET `lang_explain` = 'WeChatログイン' WHERE `type_id` = 6 AND `code` = '微信登录';
UPDATE `eb_lang_code` SET `lang_explain` = '有料会員' WHERE `type_id` = 6 AND `code` = '付费会员';
UPDATE `eb_lang_code` SET `lang_explain` = '交換' WHERE `type_id` = 6 AND `code` = '兑换';
UPDATE `eb_lang_code` SET `lang_explain` = 'ローカルキャッシュデータについて明確にしていますか' WHERE `type_id` = 6 AND `code` = '确定清楚本地缓存数据吗';
UPDATE `eb_lang_code` SET `lang_explain` = 'システムエラー' WHERE `type_id` = 6 AND `code` = '系统错误';
UPDATE `eb_lang_code` SET `lang_explain` = 'タイムセール' WHERE `type_id` = 6 AND `code` = '秒杀活动';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選に参加して残高を使用する' WHERE `type_id` = 6 AND `code` = '参与抽奖使用余额';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選の当選残高' WHERE `type_id` = 6 AND `code` = '抽奖中奖赠送余额';
UPDATE `eb_lang_code` SET `lang_explain` = '抽選当選時の付与ポイント' WHERE `type_id` = 6 AND `code` = '抽奖中奖赠送积分';
UPDATE `eb_lang_code` SET `lang_explain` = 'グループリーダーコミッションを取得する' WHERE `type_id` = 6 AND `code` = '获得拼团团长佣金';
UPDATE `eb_lang_code` SET `lang_explain` = '保留中の注文が正常に支払われました。注文番号は{:order_id}です!' WHERE `type_id` = 6 AND `code` = '500004';
UPDATE `eb_lang_code` SET `lang_explain` = 'おめでとうございます。別の有力者があなたのチームに永久にバインドされます。ユーザー{:nickname}があなたのチームに参加しました!' WHERE `type_id` = 6 AND `code` = '500005';
UPDATE `eb_lang_code` SET `lang_explain` = '購入した商品の支払いが完了しました。支払い金額は{:pay_price}元です。注文番号は{:order_id}です。ご訪問いただきありがとうございます。' WHERE `type_id` = 6 AND `code` = '500006';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、あなたの注文{:order_id}、製品{:store_name}が受領されたことを確認しました。訪問していただきありがとうございます!' WHERE `type_id` = 6 AND `code` = '500007';
UPDATE `eb_lang_code` SET `lang_explain` = 'ご注文{:order_id}、実際のお支払い金額は{:pay_price}に変更されました' WHERE `type_id` = 6 AND `code` = '500008';
UPDATE `eb_lang_code` SET `lang_explain` = 'ご注文{:order_id}は払い戻しに同意しました。払い戻し金額は{:refund_price}元です。' WHERE `type_id` = 6 AND `code` = '500009';
UPDATE `eb_lang_code` SET `lang_explain` = '{:price}のリチャージに成功しました。残高は{:now_money}元です' WHERE `type_id` = 6 AND `code` = '500010';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、ポイント{:gain_integral}、既存のポイント{:integral}の取得に成功しました' WHERE `type_id` = 6 AND `code` = '500011';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、それはとても退屈です！あなたの友人はすでにあなたのために予約価格を交渉しています。商品名は{:title}、予約価格は{:min_price}です。' WHERE `type_id` = 6 AND `code` = '500013';
UPDATE `eb_lang_code` SET `lang_explain` = 'お客様の共同購入が成立しました。グループ名：{:title}、グループ長：{:nickname}' WHERE `type_id` = 6 AND `code` = '500014';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、あなたのグループは失敗しました。イベント名は{:title}です' WHERE `type_id` = 6 AND `code` = '500015';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、あなたはグループに正常に参加しました。イベントの名前は{:title}です' WHERE `type_id` = 6 AND `code` = '500016';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、コミッション{:extract_number}元の引き出しに成功しました' WHERE `type_id` = 6 AND `code` = '500017';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、再充電された金額は返金されました。今回の返金額は{:refund_price}元です' WHERE `type_id` = 6 AND `code` = '500019';
UPDATE `eb_lang_code` SET `lang_explain` = 'こんにちは！ご注文{:order_id}は払い戻しを拒否されました。' WHERE `type_id` = 6 AND `code` = '500020';
UPDATE `eb_lang_code` SET `lang_explain` = '保留中の払い戻し注文、注文番号{:order_id}があります。' WHERE `type_id` = 6 AND `code` = '500021';
UPDATE `eb_lang_code` SET `lang_explain` = 'ユーザー{:nickname}様、商品{:store_name}、注文番号{:order_id}を発送しました。よくご確認ください。' WHERE `type_id` = 6 AND `code` = '500022';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、あなたのグループはキャンセルされました。イベント名は{:title}です' WHERE `type_id` = 6 AND `code` = '500023';
UPDATE `eb_lang_code` SET `lang_explain` = '親愛なる、あなたはグループに正常に参加しました。イベントの名前は{:title}です' WHERE `type_id` = 6 AND `code` = '500024';
UPDATE `eb_lang_code` SET `lang_explain` = '保留中の引き出しリクエストがあります。引き出し額は{:money}です!' WHERE `type_id` = 6 AND `code` = '500025';
UPDATE `eb_lang_code` SET `lang_explain` = '配送が確認された注文があります。注文番号は{:order_id}です!' WHERE `type_id` = 6 AND `code` = '500026';
UPDATE `eb_lang_code` SET `lang_explain` = '未払いの注文があります。注文番号は{:order_id}です。商品の数量には限りがあります。時間内にお支払いください。' WHERE `type_id` = 6 AND `code` = '500027';
-- 補正件数: 482

-- ============================================================
-- 5. 既定言語（管理画面の「設定 > 多言語設定」でも変更可能）
--    既定を日本語にする場合は下記2行のコメントを外してください。
-- ============================================================
-- UPDATE `eb_lang_type` SET `is_default` = 0;
-- UPDATE `eb_lang_type` SET `is_default` = 1 WHERE `id` = 6;
